# Generated by Django 3.2.3 on 2021-08-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('date', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('disc', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('free', models.BooleanField(default=False)),
            ],
        ),
    ]
